using System.IO;
using Tyuiu.KozhevnikovYV.Sprint5.Task0.V7.Lib;
DataService ds = new DataService();
int x = 4;

Console.Title = "Спринт 5 | Выполнил: Кожевников Я. В. | ПКТб-25-1";
Console.WriteLine("********************************************************************************");
Console.WriteLine("* Спринт #5                                                                    *");
Console.WriteLine("* Тема: Базовые навыки работы в C#                                             *");
Console.WriteLine("* Задание #0                                                                   *");
Console.WriteLine("* Вариант #7                                                                   *");
Console.WriteLine("* Выполнил: Кожевников Ярослав Вадимович | ПКТб-25-1                           *");
Console.WriteLine("********************************************************************************");
Console.WriteLine("* ИСХОДНЫЕ ДАННЫЕ:                                                             *");
Console.WriteLine("********************************************************************************");
Console.WriteLine("F(x) = -x^3 + 4*x^2 + 1.5 * x");
Console.WriteLine("x = " + x);
Console.WriteLine("********************************************************************************");
Console.WriteLine("* РЕЗУЛЬТАТ:                                                                   *");
Console.WriteLine("********************************************************************************");
string res = ds.SaveToFileTextData(x);
Console.WriteLine("Файл " + res);
Console.WriteLine("Создан");
Console.ReadKey();